name: Python Package using Conda

on:
  push: {} # Trigger the workflow on push events

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5 # Limit parallel jobs to 5

    steps:
    - uses: actions/checkout@v3 # Checkout the repository code
    - name: Set up Python 3.10
      uses: actions/setup-python@v2 # Corrected to v2 since v3 does not exist
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $HOME/.bashrc
        source $HOME/.bashrc
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
